Revert "snmpd: Document the possible values of the 'pdutype' argument of netsnmp_add_notification_session()"
Revert this patch since it causes the following build failure:

agent_trap.c: In function netsnmp_add_notification_session:
agent_trap.c:191:61: error: ?AGENTX_MSG_NOTIFY? undeclared (first use in this function)
                    pdutype == SNMP_MSG_INFORM || pdutype == AGENTX_MSG_NOTIFY);
                                                             ^
../include/net-snmp/library/snmp_assert.h:48:20: note: in definition of macro ?netsnmp_assert?
               if ( x ) \
                    ^
agent_trap.c:191:61: note: each undeclared identifier is reported only once for each function it appears in
                    pdutype == SNMP_MSG_INFORM || pdutype == AGENTX_MSG_NOTIFY);
                                                             ^

This reverts commit fa49aae30126605a2b5ad4ef3a5b040b6a6b8801.