darwin: fix build error due to -Wdeclaration-after-statement
With -Wdeclaration-after-statement enabled, Darwin builds now fail with:

```
mibgroup/host/data_access/swinst_darwin.c:380:17: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
  380 |     VersRecHndl versHandle = (VersRecHndl)Get1IndResource('vers', 1);
      |                 ^
```

This patch moves variable declarations to the top of the function to
satisfy pre-C99.

Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>