Darwin: Only include mibII/{ipAddr,var_route} if struct in_ifaddr is available
This patch fixes the following build error for Xcode 12 and later:

libtool: compile:  gcc -I../../include -I. -I../../agent -I../../agent/mibgroup -I../../snmplib -I/usr/local/opt/openssl@1.1/include -D_GNU_SOURCE -D_ALL_SOURCE -D_THREAD_SAFE -D__EXTENSIONS__ -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -Udarwin19 -Ddarwin19=darwin19 -Wall -Wextra -Wstrict-prototypes -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-parameter -Wno-type-limits -Wno-deprecated-declarations -c mibII/ipAddr.c  -fno-common -DPIC -o mibII/.libs/ipAddr.o
1480mibII/ipAddr.c:206:29: error: variable has incomplete type 'struct in_ifaddr'
1481    static struct in_ifaddr in_ifaddr, lowin_ifaddr;
1482                            ^