AgentX, MSVC: Fix a recently introduced build error
Avoid that the following error and warnings are reported:

..\..\agent\mibgroup\agentx\protocol.c(1249): error C2036: 'void *': unknown size
..\..\agent\mibgroup\agentx\protocol.c(1560): warning C4146: unary minus operator applied to unsigned type, result still unsigned
..\..\agent\mibgroup\agentx\protocol.c(1565): warning C4146: unary minus operator applied to unsigned type, result still unsigned
..\..\agent\mibgroup\agentx\protocol.c(1570): warning C4146: unary minus operator applied to unsigned type, result still unsigned