SNMP-USM-DH-OBJECTS-MIB: Fix a compiler warning
Avoid that the following warning is reported when building against an
older openssl library:

snmp-usm-dh-objects-mib/usmDHParameters/usmDHParameters.c: In function 'init_usmDHParameters':
snmp-usm-dh-objects-mib/usmDHParameters/usmDHParameters.c:44:9: warning: implicit declaration of function 'DH_set0_pqg' [-Wimplicit-function-declaration]
         DH_set0_pqg(dh_params, p, NULL, g);
         ^

See also commit 3317a7c66362 ("Remove duplicated function in usmDHParameters.c that breaks compilation with LibreSSL 2.7.2 (OpenBSD 6.3)")