ucd-snmp/extensible.h: Add config_require(ucd-snmp/pass)
Since this module calls pass_compare(), add a dependency on ucd-snmp/pass.
This patch fixes the following runtime error on Darwin:

dyld: Symbol not found: _pass_compare
  Referenced from: /Users/travis/build/bvanassche/net-snmp/agent/.libs/libnetsnmpmibs.40.dylib
  Expected in: flat namespace
 in /Users/travis/build/bvanassche/net-snmp/agent/.libs/libnetsnmpmibs.40.dylib