Windows: Fix the build
Fix the following linker error:

netsnmpagent.lib(snmp_vars.obj) : error LNK2019: unresolved external symbol netsnmp_certs_shutdown referenced in function shutdown_agent

Fixes: 80709f87e379 ("snmpd: Fix memory leaks at shutdown time related to the cert code")