testing: Skip building the fuzz tests on OS/X and MinGW
Skip building the fuzz tests on OS/X and MinGW since building the fuzz tests
fails on these operating systems. On OS/X the following is reported:

In file included from /Users/appveyor/projects/net-snmp/testing/fuzzing/agentx_parse_fuzzer.c:31:
In file included from include/net-snmp/net-snmp-includes.h:38:
In file included from include/net-snmp/snmpv3_api.h:29:
include/net-snmp/library/scapi.h:14:10: fatal error: 'openssl/ossl_typ.h' file not found
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

The MinGW build fails as follows:

In file included from C:/projects/net-snmp/testing/fuzzing/agentx_parse_fuzzer.c:31:
In file included from include\net-snmp/net-snmp-includes.h:31:
include\net-snmp/utilities.h:31:10: fatal error: 'getopt.h' file not found
 #include <getopt.h>
         ^~~~~~~~~~
1 error generated.