include/net-snmp/types.h: Unbreak the MinGW build
Revert the two most recent changes to this header file to avoid that the MSYS2
build fails as follows:

util_funcs.c:406:1: error: conflicting types for 'get_exec_pipes'
 get_exec_pipes(char *cmd, int *fdIn, int *fdOut, netsnmp_pid_t *pid)
 ^~~~~~~~~~~~~~
In file included from util_funcs.c:91:0:
util_funcs.h:40:17: note: previous declaration of 'get_exec_pipes' was here
 int             get_exec_pipes(char *cmd, int *fdIn, int *fdOut, HANDLE *pid);
                 ^~~~~~~~~~~~~~